version: '3.8'

services:  
  php_fpm:
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    working_dir: /var/www/
    container_name: leru_php_fpm
    volumes:
      - leru-volume:/var/www

  nginx_url:
    image: nginx:latest
    container_name: leru_nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - leru-volume:/var/www/
    depends_on:
      - php_fpm
    ports:
      - "80:80"

networks:
  default:
    external:
      name: external-example