version: '3.8'
services:
    web:
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
            args:
                uid: ${UID}
        environment:
            - APACHE_RUN_USER=#${UID}
            - APACHE_RUN_GROUP=#${UID}
        restart: unless-stopped
        volumes: 
            - ./src:/var/www/html
            - ./apache_log:/var/log/apache2
        ports:
            - 80:80
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080

networks:
  default:
    external:
      name: external-example