version: '3.8'
services:
    ci4-web:
        build:
            context: ./php
        command: ./php spark serve
        ports:
            - 80:80
        volumes:
            - .:/var/www/html/
networks:
  default:
    external:
      name: external-example