version: '3'
services:
    ci4-web:
        build:
            context: ./php
        ports:
            - 80:80
        volumes:
            - ../app:/var/www/html/app/
networks:
  default:
    external:
      name: external-example